

#ifndef VARIABLES_H
#define VARIABLES_H


#define WINDOW_WIDTH 1280 // 1920
#define WINDOW_HEIGHT 720 // 1080

#define TILE_SIZE 32

#define TILES_TEXTURE_COUNT 4

#define SOLID_TILES_COUNT 2
#define TRANSPARENT_TILES_COUNT 2

#define ENTITY_TEXTURE_COUNT 3

#define FONT_LETTER_COUNT 26
#define FONT_NUMBER_COUNT 10
#define FONT_TEXTURE_COUNT (FONT_LETTER_COUNT + FONT_NUMBER_COUNT)


#define DEFAULT_MAP_WIDTH 1000
#define DEFAULT_MAP_HEIGHT 1000

#define MAP_RENDER_WIDTH (WINDOW_WIDTH / TILE_SIZE + 1)
#define MAP_RENDER_HEIGHT (WINDOW_HEIGHT / TILE_SIZE + 1)

#define MAX_AREA_WIDTH (3 * MAP_RENDER_WIDTH * TILE_SIZE / 4)
#define MAX_AREA_HEIGHT (2 * MAP_RENDER_HEIGHT * TILE_SIZE / 3)

#define FONT_SIZE_INTERFACE 24

#define F_DELTA 16

#define PLAYER_DEFAULT_MOVING_SPEED 400

#define MAX_FILENAME_LENGTH 50

#define DIALOGUE_OFFSET 20


#endif